# Theme
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

# Page settings
title: Rodolfo Pietro Articles
logo: /assets/img/me.png
description: Here you can find all my articles and publications.
show_downloads: false
